---
title: "Metodología"
author: "Eduardo PM"
date: "2023-06-15"
output:
  bookdown::gitbook: default
  citation_package: biblatex
  extra_dependencies: null
  amsmath: null
  cancel: makeroom
  bookdown::pdf_book:
    keep_tex: yes
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
header_includes: null
output_dir: "docs"
---
<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("TeX Jax Ready",function () {
  MathJax.Hub.Insert(MathJax.InputJax.TeX.Definitions.macros,{
    cancel: ["Extension","cancel"],
    bcancel: ["Extension","cancel"],
    xcancel: ["Extension","cancel"],
    cancelto: ["Extension","cancel"]
  });
});
</script>
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# MÉTODOS 

## Datos genómicos

Se descargaron 2 conjuntos de genomas de cianobacterias del servidor del NCBI (https://www.ncbi.nlm.nih.gov/genome/browse/#!/prokaryotes).  

Estos conjuntos corresponden a:

* 269 genomas completos y aquellos que solo contenian el cromosoma (**complete_chr**)

* 165 genomas nuevos usados en @{cabello2022elucidating} (**pico**)

Dichos genomas fueron descargados en formato Genebank (**.gbk** o **gbff**). 

## Abundancia de palíndromos. 

Una vez descargados los genomas, el siguiente paso fue calcular el valor observado y esperado de repeticiones de todos los posibles octámeros palindrómicos de 8 nucleótidos. 

El valor observado es el número de veces que cada octámero palindrómico se repite a lo largo de cada genoma. 
El valor esperado se calculó mediante un **modelo de markov de 3er orden**.